version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: docs/requirements.txt
    # Install the Read the Docs python package before building Sphinx module
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
